// <auto-generated />
using System;
using BroadwayShows.Library.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BroadwayShows.Library.Migrations
{
    [DbContext(typeof(BroadwayShowsContext))]
    [Migration("20231103030218_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BroadwayShows.Library.Models.CastCrew", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("TheaterId")
                        .HasColumnType("int");

                    b.Property<string>("WorkingPosition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SSN");

                    b.HasIndex("ShowId");

                    b.HasIndex("TheaterId");

                    b.ToTable("CastCrews");
                });

            modelBuilder.Entity("BroadwayShows.Library.Models.Shows", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShowId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("BroadwayShows.Library.Models.Theater", b =>
                {
                    b.Property<int>("TheaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.HasKey("TheaterId");

                    b.ToTable("Theaters");
                });

            modelBuilder.Entity("BroadwayShows.Library.Models.TicketSales", b =>
                {
                    b.Property<int>("TicketNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TheaterId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.HasKey("TicketNumber");

                    b.HasIndex("TheaterId");

                    b.ToTable("TicketSales");
                });

            modelBuilder.Entity("BroadwayShows.Library.Models.CastCrew", b =>
                {
                    b.HasOne("BroadwayShows.Library.Models.Shows", "Show")
                        .WithMany("CastCrews")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BroadwayShows.Library.Models.Theater", "Theater")
                        .WithMany("CastCrews")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("BroadwayShows.Library.Models.TicketSales", b =>
                {
                    b.HasOne("BroadwayShows.Library.Models.Theater", "Theater")
                        .WithMany("TicketSales")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("BroadwayShows.Library.Models.Shows", b =>
                {
                    b.Navigation("CastCrews");
                });

            modelBuilder.Entity("BroadwayShows.Library.Models.Theater", b =>
                {
                    b.Navigation("CastCrews");

                    b.Navigation("TicketSales");
                });
#pragma warning restore 612, 618
        }
    }
}
